### ISSUE TITLE
Broken Reference in Version 0.0.3

### ISSUE THREAD

**Issue by felixfuchs17** [kaihenzler/node-mcp23017#4]
Unfortunately, it seems that a variable is no longer defined, because everything still works in version 0.0.2.
I get the following error:

/node_modules/node-mcp23017/lib/mcp23017.js:136
this._send(register, [registerDir]);

I am using node 8.11.1
The operating system is the latest version of RASPBIAN STRETCH.

**Comment by kaihenzler** [comment]
Does your commit fix the issue? If so, I would be very happy if you could create a PR
